version: "3.8"

services:
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pulse_pgadmin
    depends_on:
      - db
    environment:
      PGADMIN_DEFAULT_EMAIL: pulse@manush.tech
      PGADMIN_DEFAULT_PASSWORD: pulse@456
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "4040:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    links:
      - db:pgsql-server
    restart: always

volumes:
  pgadmin-data:
